live_config_reload = true

[cursor.style]
blinking = "Always"

[font]
size = 12.0

[font.bold]
family = "Cousine Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Cousine Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Cousine Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Cousine Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["-nologo"]
program = "pwsh"

[window]
dynamic_title = false
opacity = 0.7
startup_mode = "Maximized"
title = "Alacritty"

[window.padding]
x = 8
y = 8
